---
- service:
   name: docker
   state: started
- file:
    path: "{{ jjjPod_build_dir }}"
    state: directory
    recurse: yes
- group:
    name: "{{ jjjPod_group }}"
    gid: "{{ jjjPod_gid }}"
- user:
    name: "{{ jjjPod_user }}"
    uid: "{{ jjjPod_uid }}"
    group: "{{ jjjPod_group }}"
- copy:
    src: "{{ item }}"
    dest: "{{ jjjPod_build_dir }}"
  with_items: "{{ jjjPod_docker_ingredients }}"

# data container
- docker:
    image: alpine
    name: jjjpod-nginx-data
    state: restarted
    pull: missing
    volumes:
      - "{{ jjjPod_build_dir }}/nginx-location.conf:/etc/nginx/locations.d/timcinel-jjjpod/location.conf"
    command: /bin/true
    net: timcinel

# app container
- shell: "docker build -t {{ jjjPod_docker_image }} ."
  args:
    chdir: "{{ jjjPod_build_dir }}"
- docker:
    image: "{{ jjjPod_docker_image }}"
    name: jjjpod
    state: restarted
    restart_policy: unless-stopped
    pull: missing
    memory_limit: "{{ jjjPod_docker_memory_limit }}"
    net: "{{ jjjPod_docker_network }}"
    env:
      DOCKER_USER: "{{ jjjPod_user }}"
      DOCKER_USER_ID: "{{ jjjPod_uid }}"
      DOCKER_GROUP: "{{ jjjPod_group }}"
      DOCKER_GROUP_ID: "{{ jjjPod_gid }}"
